# This workflow will do a clean install of dependencies, and compile the typescript.

name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ["22"]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

            - name: Install Dependencies
              run: npm i
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.CI_KEY }}

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
